name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ] # ou master selon ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Version 20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Yarn)
        run: yarn install

      - name: Build project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # (Remplace par './dist' si ton dossier de build s'appelle dist)
