name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ] # ou master selon ta branche

# 1. AJOUTER CE BLOC PERMISSIONS ICI
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Yarn)
        run: yarn install

      - name: Build project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build

      - name: Deploy to GitHub Pages
        # 2. UTILISER v4 ICI AU LIEU DE v3
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # (ou ./dist selon ton dossier de sortie)
